spring.application.name=product-service

#Database
spring.data.mongodb.uri=mongodb+srv://julianmarcelolopez:FAkGuvYwXhk8o91Q@cluster0.yawaz.mongodb.net/productdb?retryWrites=true&w=majority

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.bootstrap-servers=csfv2tm7lc8s5d75lme0.any.us-east-1.mpx.prd.cloud.redpanda.com:9092

# Configuración de seguridad (autenticación SASL/SSL)
#spring.kafka.properties.security.protocol=SASL_SSL
#spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
#spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="userpanda" password="passpanda";
#spring.kafka.properties.ssl.endpoint.identification.algorithm=https

logging.level.org.apache.kafka=DEBUG

# Ajustes de tiempo de espera y reconexión
spring.kafka.properties.request.timeout.ms=60000
spring.kafka.properties.retry.backoff.ms=500
spring.kafka.properties.reconnect.backoff.max.ms=10000


# Producer Config
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.jlsolutions.commons.ProductEvent